---
title: "SN4741_qPCR_graph"
author: "Rachel Boyd"
date: "2022-09-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading packages & reading in data:
```{r}
library(svglite)
library(ggplot2)
library(readxl)
qPCR <- read_excel("C:/Users/rboyd25/OneDrive - Johns Hopkins/Documents/Hopkins/McCallion/Papers/SN4741/qPCR/qPCR.xlsx")
```

Graph:
```{r}
cbPalette <- c("#332288","#117733","#ddcc77","#cc6677")

plot1 <- ggplot(qPCR, aes(x=interaction(target_name, sample_name, lex.order = T), y=fold_change, fill=target_name)) + 
  geom_bar(stat = "identity", 
           position = position_dodge(),
           color = "black",
           size = 1) +
  scale_fill_manual(values=cbPalette) +
  geom_errorbar(aes(ymin=fold_change-neg_err,ymax=fold_change+pos_err),width=.3,size=1, position=position_dodge(0.9)) +
  annotate(geom = "text", x = seq(1.5,7.5, 2), y = -0.4, 
           label = sort(unique(qPCR$target_name)), 
           size = 6,fontface = 'italic') +
  annotate(geom = "text", 
           x = 1+2*(0:3), y = -0.2, 
           label =  qPCR$sample_name[qPCR$sample_name == "37"], size = 5) +
  annotate(geom = "text", 
           x = 2+2*(0:3), y = -0.2, 
           label =  qPCR$sample_name[qPCR$sample_name == "39"], size = 5) +
  coord_cartesian(ylim = c(0, 3.5), expand = FALSE, clip = "off") +
  xlab(paste0("")) +
  ylab("Relative Fold Change in Expression") +
  theme_classic() +
  theme(
    legend.position = "none",
    plot.margin = unit(c(1, 1, 3, 1), "lines"),
  axis.text.x = element_blank(),
  axis.text.y = element_text(size = 14, color = "black"),
  axis.title.y = element_text(size = 18),
  panel.border = element_rect(color = "black", fill = "transparent",size=1))
    
ggsave('SN4741_qPCR.pdf', width = 7, height = 6, plot1)
```

